In [1]:
import keras
from keras import models
from keras import layers

import tensorflow as tf
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
session = tf.Session(config=config)

Using TensorFlow backend.


In [2]:
import numpy as np

In [3]:
data_in = np.matrix('0 0; 0 1; 1 0; 1 1')

In [4]:
print(data_in)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [5]:
logic_and = np.matrix('0; 0; 0; 1')
print(logic_and)

[[0]
 [0]
 [0]
 [1]]


In [6]:
logic_or = np.matrix('0; 1; 1; 1')

In [9]:
logic_xor = np.matrix('0; 1; 1; 0')

In [13]:
model_and = keras.models.Sequential()
model_and.add(layers.Dense(1, activation = 'sigmoid', input_shape = (2,)))

model_and.compile(optimizer=keras.optimizers.SGD(lr=.5), loss='binary_crossentropy')

In [14]:
keras.backend.eval(model_and.weights[0])

array([[-0.9096942 ],
       [-0.75851345]], dtype=float32)

In [10]:
model_and.predict(np.array([[1,1]]))

array([[0.29733568]], dtype=float32)

In [16]:
model_and.fit(data_in, logic_and, epochs = 1000, verbose=False)

In [20]:
model_and.predict(np.array([[1,0]]))

array([[0.5]], dtype=float32)

In [16]:
model_xor = keras.models.Sequential()
model_xor.add(layers.Dense(2, activation = 'sigmoid', input_shape = (2,)))
model_xor.add(layers.Dense(1, activation = 'sigmoid'))

model_xor.compile(optimizer=keras.optimizers.SGD(lr=.5), loss='binary_crossentropy')

In [17]:
keras.backend.eval(model_xor.weights[0])

array([[-0.74731183,  0.983909  ],
       [-0.5295657 , -0.7663328 ]], dtype=float32)

In [7]:
model_xor.weights

[<tf.Variable 'dense_1/kernel:0' shape=(2, 2) dtype=float32_ref>,
 <tf.Variable 'dense_1/bias:0' shape=(2,) dtype=float32_ref>,
 <tf.Variable 'dense_2/kernel:0' shape=(2, 1) dtype=float32_ref>,
 <tf.Variable 'dense_2/bias:0' shape=(1,) dtype=float32_ref>]

In [14]:
model_xor.fit(data_in, logic_xor, epochs = 1000, verbose=False)

In [15]:
model_xor.predict(np.array([[0,0]]))

array([[0.00996762]], dtype=float32)